import { PASSIVES, WEAPONS } from '../sim/content';
import type { Card } from '../sim/types';
import { ICONS16 } from './icons16';

/** Power icons (16×16, generated by tools/icons16.py). */
export const ICONS: Readonly<Record<string, readonly string[]>> = ICONS16;

export function iconFor(card: Card): readonly string[] {
  if (card.kind === 'heal') return ICONS.heal;
  if (card.kind === 'evolution') return ICONS.evolution;
  return ICONS[card.id as string];
}

/** Icon for a build line such as "Bone Storm Lv 8" or "Magnet Lv 2" (weapon, evolved weapon or passive name). */
export function iconForLabel(label: string): readonly string[] | null {
  const name = label.replace(/ Lv \d+$/, '');
  for (const [id, w] of Object.entries(WEAPONS)) if (w.name === name || w.evolvedName === name) return ICONS[id] ?? null;
  for (const [id, p] of Object.entries(PASSIVES)) if (p.name === name) return ICONS[id] ?? null;
  return null;
}
