// Developer tool: snapshot the walk-left/right art of real minted Generations Friends from the on-chain registry
// into games/stay-rare/render/enemyFriends.ts (enemy art; no runtime chain reads, so `friendsdk test` keeps passing).
// Usage: node tools/snapshot-friends.mjs [common-per-family=4] [rare-per-family=2]
import { writeFile } from 'node:fs/promises';
import { createPublicClient, http, parseAbi } from 'viem';
import { FAMILIES_REGISTRY_ABI, GENERATION_FAMILY_NAMES, GENERATION_SPRITE_MANIFEST } from '@rarefriends/friendsdk/sprites';

const [common = 4, rare = 2] = process.argv.slice(2).map(Number);
const want = GENERATION_FAMILY_NAMES.map((_, id) => (id <= 4 ? common : rare));
const chain = createPublicClient({ transport: http(GENERATION_SPRITE_MANIFEST.rpcUrl, { batch: true, retryCount: 3 }) });
const registry = GENERATION_SPRITE_MANIFEST.registry, ownerAbi = parseAbi(['function ownerOf(uint256) view returns (address)']);
const picked = GENERATION_FAMILY_NAMES.map(() => []), tried = new Set();
let reads = 0;
while (picked.some((list, id) => list.length < want[id]) && reads < 4000) {
  const ids = Array.from({ length: 20 }, () => BigInt(1 + Math.floor(Math.random() * 20000))).filter(id => !tried.has(id));
  ids.forEach(id => tried.add(id));
  const families = await Promise.all(ids.map(id => chain.readContract({ address: registry, abi: FAMILIES_REGISTRY_ABI, functionName: 'familyOf', args: [id] }).catch(() => null)));
  reads += ids.length;
  for (let i = 0; i < ids.length; i++) {
    const family = families[i];
    if (family === null || picked[family].length >= want[family]) continue;
    try { await chain.readContract({ address: GENERATION_SPRITE_MANIFEST.generations, abi: ownerAbi, functionName: 'ownerOf', args: [ids[i]] }); }
    catch { continue; } // only minted Friends
    const seed = await chain.readContract({ address: registry, abi: FAMILIES_REGISTRY_ABI, functionName: 'seedOf', args: [ids[i]] });
    const frames = await chain.readContract({ address: registry, abi: FAMILIES_REGISTRY_ABI, functionName: 'frames', args: [family, seed] });
    // Frame order (FriendSDK decodeGenerationSprites): idle down/up/left/right, then walk down/up/left/right; 8 each.
    picked[family].push({ tokenId: Number(ids[i]), familyId: family, left: frames.slice(48, 56).map(f => f.toString(16)), right: frames.slice(56, 64).map(f => f.toString(16)) });
    process.stdout.write(`#${ids[i]} ${GENERATION_FAMILY_NAMES[family]}  `);
  }
}
const all = picked.flat();
const body = `// Generated by tools/snapshot-friends.mjs on ${new Date().toISOString().slice(0, 10)} from the Rare Friends Generations
// registry ${registry} (Robinhood Chain 4663): walk-left/right frames of ${all.length} real minted Friends, used as
// the glitched enemies. Canonical Rare Friends Generations artwork; see FriendSDK NOTICE.md. Do not edit by hand.
export type EnemyFriend = Readonly<{ tokenId: number; familyId: number; left: readonly string[]; right: readonly string[] }>;
export const ENEMY_FRIENDS: readonly EnemyFriend[] = ${JSON.stringify(all, null, 0).replace(/\},\{/g, '},\n  {')};
`;
await writeFile('games/stay-rare/render/enemyFriends.ts', body);
console.log(`\n${all.length} Friends (${picked.map((l, i) => `${GENERATION_FAMILY_NAMES[i]} ${l.length}`).join(', ')}) after ${reads} family reads`);
